package Vista.Cursos;

import Vista.Profesores.*;
import Modelo.Conexion;
import Vista.Principal;
import java.sql.Array;
import java.util.Date;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeArray.map;

public class CrearCurso extends javax.swing.JDialog {
    
    /*Se crea una variable para hacer la conexión con la pantalla Principal*/
    private Principal principal;
    private ListadoProfesores listado;
    
    /**
     * Creates new form CrearProfesor
     */
    public CrearCurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        /*Se hace la conexión con la pantalla Principal*/
        principal = (Principal)parent;
        initComponents();
        /*Centramos la ventana del diálogo CrearCurso*/
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        ContenidoCrearCurso = new javax.swing.JPanel();
        NombreCurso = new javax.swing.JLabel();
        NivelCurso = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        DuracionCurso = new javax.swing.JLabel();
        DescripcionCurso = new javax.swing.JLabel();
        FechaAltaProfesor = new javax.swing.JLabel();
        FechaBajaProfesor = new javax.swing.JLabel();
        TextoDuracionCurso = new javax.swing.JTextField();
        TextoNombreCurso = new javax.swing.JTextField();
        FechaAlta = new com.toedter.calendar.JDateChooser();
        FechaBaja = new com.toedter.calendar.JDateChooser();
        TextoPrecioCurso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDescripcionCurso = new javax.swing.JTextArea();
        ComoNivelCurso = new javax.swing.JComboBox<>();
        BotoneraInferior = new javax.swing.JPanel();
        CancelarCurso = new javax.swing.JButton();
        CrearCurso = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelCrearCurso = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        ContenidoCrearCurso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NombreCurso.setText("Nombre");

        NivelCurso.setText("Nivel");

        Precio.setText("Precio");

        DuracionCurso.setText("Duración");

        DescripcionCurso.setText("Descripción");

        FechaAltaProfesor.setText("Fecha Alta");

        FechaBajaProfesor.setText("Fecha Baja");

        TextAreaDescripcionCurso.setColumns(20);
        TextAreaDescripcionCurso.setRows(5);
        jScrollPane1.setViewportView(TextAreaDescripcionCurso);

        ComoNivelCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Avanzado" }));

        javax.swing.GroupLayout ContenidoCrearCursoLayout = new javax.swing.GroupLayout(ContenidoCrearCurso);
        ContenidoCrearCurso.setLayout(ContenidoCrearCursoLayout);
        ContenidoCrearCursoLayout.setHorizontalGroup(
            ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoCrearCursoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoNombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(NombreCurso)
                    .addComponent(NivelCurso)
                    .addComponent(TextoPrecioCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(Precio)
                    .addComponent(DuracionCurso)
                    .addComponent(TextoDuracionCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(ComoNivelCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescripcionCurso)
                    .addComponent(FechaAltaProfesor)
                    .addComponent(FechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaBajaProfesor)
                    .addComponent(FechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        ContenidoCrearCursoLayout.setVerticalGroup(
            ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoCrearCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCurso)
                    .addComponent(DescripcionCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoCrearCursoLayout.createSequentialGroup()
                        .addComponent(TextoNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NivelCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComoNivelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(10, 10, 10)
                .addGroup(ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio)
                    .addComponent(FechaAltaProfesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DuracionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FechaBajaProfesor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoCrearCursoLayout.createSequentialGroup()
                        .addGroup(ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoPrecioCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)))
                .addGroup(ContenidoCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextoDuracionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        CancelarCurso.setText("Cancelar");
        CancelarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCursoActionPerformed(evt);
            }
        });

        CrearCurso.setText("Crear");
        CrearCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotoneraInferiorLayout = new javax.swing.GroupLayout(BotoneraInferior);
        BotoneraInferior.setLayout(BotoneraInferiorLayout);
        BotoneraInferiorLayout.setHorizontalGroup(
            BotoneraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoneraInferiorLayout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(CancelarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CrearCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BotoneraInferiorLayout.setVerticalGroup(
            BotoneraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoneraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CancelarCurso)
                .addComponent(CrearCurso))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabelCrearCurso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCrearCurso.setText("NUEVO CURSO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabelCrearCurso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCrearCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotoneraInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContenidoCrearCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ContenidoCrearCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotoneraInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCursoActionPerformed
        /*Programamos el retorno a la pantalla principal*/
        this.setVisible(false);
        new Principal().setVisible(true);
    }//GEN-LAST:event_CancelarCursoActionPerformed

    private void CrearCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCursoActionPerformed
        
        try 
        {
            /*Recogemos toda la información introducida del curso a crear*/
            String nombre_curso = TextoNombreCurso.getText().trim();
            String descripcion_curso = TextAreaDescripcionCurso.getText().trim();
            String nivel_curso = (String)ComoNivelCurso.getSelectedItem();
            String precio_curso = TextoPrecioCurso.getText().trim();
            String duracion_curso = TextoDuracionCurso.getText().trim();
            String fechaAlta_curso = formateaFecha(FechaAlta.getDate()).trim();
            String fechaBaja_curso = formateaFecha(FechaBaja.getDate()).trim();
            
            /*Abrimos conexión con la base de datos*/
            Connection conexion = Conexion.conexionPostgresql();
            ResultSet nombre_nivel_cursos_bd = conexion.createStatement().executeQuery("select Nombre, Nivel from Cursos");
            HashMap<String, String> diccionario_nombre_nivel_cursos = new HashMap<String, String>();
            while(nombre_nivel_cursos_bd.next())
            {
                String columna_nombre_bd = nombre_nivel_cursos_bd.getString(2);
                String columna_nivel_bd = nombre_nivel_cursos_bd.getString(4);
                diccionario_nombre_nivel_cursos.put(columna_nombre_bd, columna_nivel_bd);                
            }
            
            /*Comprobamos que los valores de entrada no sean nulos. Únicamente puede ser nulo fechaBaja_curso*/
            if(nombre_curso.isEmpty() || nombre_curso.equals(""))
            {
                JOptionPane.showMessageDialog(null,"El campo nombre es obligatorio");
                return;
            }
            if(descripcion_curso.isEmpty() || descripcion_curso.equals(""))
            {
                JOptionPane.showMessageDialog(null,"El campo descripción es obligatorio");
                return;
            }
            if(precio_curso.isEmpty() || precio_curso.equals(""))
            {
                JOptionPane.showMessageDialog(null,"El campo precio es obligatorio");
                return;
            }
            if(duracion_curso.isEmpty() || duracion_curso.equals(""))
            {
                JOptionPane.showMessageDialog(null,"El campo duración es obligatorio");
                return;  
            }
            if(fechaAlta_curso.isEmpty() || fechaAlta_curso.equals(""))
            {
                JOptionPane.showMessageDialog(null,"El campo fecha de alta es obligatorio");
                return;
            }
            
            Set <String> nombres_curso_bd = diccionario_nombre_nivel_cursos.keySet();
            Iterator it = diccionario_nombre_nivel_cursos.keySet().iterator();
            while (it.hasNext())
            {
                String nivel_curso_bd = diccionario_nombre_nivel_cursos.get(nombre_curso);
            }

            
            /*Añadimos el nuevo curso*/
            Statement sentencia = conexion.createStatement();
            ResultSet id = sentencia.executeQuery("select max(id) from Cursos");
            int max_id_curso = 0;
            while(id.next())
            {
                max_id_curso = id.getInt(1);
            }
            String inserta_curso = "";
            if (fechaBaja_curso.equals(""))
            {
                inserta_curso = "insert into Cursos values (" + (max_id_curso+1) + ",'"+nombre_curso+"','"+descripcion_curso+"','"+Double.parseDouble(precio_curso)+"','"+Integer.parseInt(duracion_curso)+"','"+fechaAlta_curso+"')";
            } 
            else
            {
                inserta_curso = "insert into Cursos values (" + (max_id_curso+1) + ",'"+nombre_curso+"','"+descripcion_curso+"','"+Double.parseDouble(precio_curso)+"','"+Integer.parseInt(duracion_curso)+"','"+fechaAlta_curso+"','"+fechaBaja_curso+"')";
            }
            sentencia.execute(inserta_curso);
            
            /*Cerramos la conexion*/
            sentencia.close();
            conexion.close();

            /*Con esta función se destruye el formulario*/
            dispose();
            /*Mostramos mensaje de éxito*/
            JOptionPane.showMessageDialog(null, "Operación realizada correctamente");
            
        } catch (SQLException ex) 
        {
            Logger.getLogger(CrearCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (NumberFormatException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_CrearCursoActionPerformed

    /*Método que transforma una fecha al formato "dd/MM/yyyy"*/
    public String formateaFecha (Date fecha)
    {   
        String fecha_bd = "";
        if(fecha == null)
        {
            String _fecha  = "";
            return _fecha;
        } 
        else
        {
            Calendar calendario = Calendar.getInstance();
            calendario.setTime(fecha);
            String dia = Integer.toString(calendario.get(Calendar.DAY_OF_MONTH));
            String mes = Integer.toString(calendario.get(Calendar.MONTH) + 1);
            String anio = Integer.toString(calendario.get(Calendar.YEAR));
            fecha_bd = dia + "/" + mes + "/" + anio;  
            return fecha_bd;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearCurso dialog = new CrearCurso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotoneraInferior;
    private javax.swing.JButton CancelarCurso;
    private javax.swing.JComboBox<String> ComoNivelCurso;
    private javax.swing.JPanel ContenidoCrearCurso;
    private javax.swing.JButton CrearCurso;
    private javax.swing.JLabel DescripcionCurso;
    private javax.swing.JLabel DuracionCurso;
    private com.toedter.calendar.JDateChooser FechaAlta;
    private javax.swing.JLabel FechaAltaProfesor;
    private com.toedter.calendar.JDateChooser FechaBaja;
    private javax.swing.JLabel FechaBajaProfesor;
    private javax.swing.JLabel NivelCurso;
    private javax.swing.JLabel NombreCurso;
    private javax.swing.JLabel Precio;
    private javax.swing.JTextArea TextAreaDescripcionCurso;
    private javax.swing.JTextField TextoDuracionCurso;
    private javax.swing.JTextField TextoNombreCurso;
    private javax.swing.JTextField TextoPrecioCurso;
    private javax.swing.JLabel jLabelCrearCurso;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
